new file:   toDV 	modified:   toX264crf

diff --git a/bin/toDV b/bin/toDV
--- a/bin/toDV
+++ b/bin/toDV
@@ -9,14 +9,14 @@ encode()  { # put your encoding settings here
     when=$(date +%Y%m%d%H%M%S)
     FFREPORT=file="$log/$baseext.$when.$RANDOM.$me.log":level=40 \
     \
-    ffmpeg -hide_banner -i "$file" -pix_fmt yuv420p -aspect 16:9 -vf yadif=0 -vcodec libx264 -preset fast -tune film -crf 21 -threads 0 -an "$tmpdir/$base.video.mp4" -movflags +faststart -loglevel panic -stats
+    ffmpeg -hide_banner -i "$file" -vf scale=720:576 -aspect 1.778 -target pal-dv "$tmpdir/$base.dv" -loglevel panic -stats
     
 }
 
 # -loglevel panic -stats
 
 # help
-    if [ $# -eq 0 ]; then echo "anything to x264 crf mode with some AAC audio"; exit 1; fi
+    if [ $# -eq 0 ]; then echo "anything to DV"; exit 1; fi
 
 # source config file which includes tmpdir generator and timer
 config="$HOME/bin/singularity.cfg"
@@ -34,24 +34,17 @@ while [ $# -gt 0 ]; do
     
         hasVideo "$file" || { >&2 echo "No Video in $file" ; shift; continue; } # "continue" should skip to next file in this while loop.
     
-        hasAudio "$file" && toAAC scriptcall "$tmpdir" "$1" >/dev/null 2>&1 & # remove >/dev/null 2>&1 when debuging
-        
         echo "$me encoding $file"
         encode "$file"
         
-        wait
+
 
     # if there is audio, then mux video + audio, else just mv video to final location.
-    if hasAudio "$file" ; then
-        echo "hasAudio, muxing"
-        ffmpeg -y -i "$tmpdir/$base.video.mp4" -i "$tmpdir/$base.m4a" -acodec copy -vcodec copy "$out/$base.mp4" -loglevel panic -movflags +faststart
-    else
-        echo "noAudio, just moving"
-        mv "$tmpdir/$base.video.mp4" "$out/$base.mp4" 
-    fi
+    mv "$tmpdir/$base.dv" "$out/$base.dv" 
+
     
     # echo output location/filename
-    test -f "$out/$base.mp4" && echo "$me output $out/$base.mp4" || { echo "$me No output file found, error, exiting" ; exit 1; }
+    test -f "$out/$base.dv" && echo "$me output $out/$base.dv" || { echo "$me No output file found, error, exiting" ; exit 1; }
     
     echo #empty line
     
