toPRORES and unique ouout filenames

diff --git a/bin/toPRORES b/bin/toPRORES
--- a/bin/toPRORES
+++ b/bin/toPRORES
@@ -9,15 +9,14 @@ encode()  { # put your encoding settings here
     when=$(date +%Y%m%d%H%M%S)
     FFREPORT=file="$log/$baseext.$when.$RANDOM.$me.log":level=40 \
     \
-    ffmpeg -hide_banner -i "$file" -vf scale=720:576 -aspect 1.778 -target pal-dv "$tmpdir/$base.dv" -loglevel panic -stats </dev/null
+    ffmpeg -hide_banner -i "$file" -vf scale=1920:1080 -c:v prores -profile:v 3 -pix_fmt yuv422p10le -acodec pcm_s16le "$tmpdir/$base.mov" -loglevel panic -stats </dev/null
     # </dev/null is some sort of null input, so that script will work when in bg as well
-    
 }
 
 # -loglevel panic -stats
 
 # help
-    if [ $# -eq 0 ]; then echo "anything to DV"; exit 1; fi
+    if [ $# -eq 0 ]; then echo "anything to PRORES.mov"; exit 1; fi
 
 # source config file which includes tmpdir generator and timer
 config="$HOME/bin/singularity.cfg"
@@ -33,22 +32,21 @@ while [ $# -gt 0 ]; do
     base="${baseext%.*}"           # file
 
     
-        hasVideo "$file" || { >&2 echo "No Video in $file" ; shift; continue; } # "continue" should skip to next file in this while loop.
-    
-        echo "$me encoding $file"
-        encode "$file"
+    hasVideo "$file" || { >&2 echo "No Video in $file" ; shift; continue; } # "continue" should skip to next file in this while loop.
+    echo "$me encoding $file"
+    encode "$file"
         
     # unique output filename
     baseout="$base" 
-    while [ -f "$out/$baseout.dv" ] ; do
+    while [ -f "$out/$baseout.mov" ] ; do
         baseout="$base.$RANDOM"
     done
         
     # if there is audio, then mux video + audio, else just mv video to final location.
-    mv "$tmpdir/$base.dv" "$out/$baseout.dv" 
-    
+    mv "$tmpdir/$base.mov" "$out/$baseout.mov" 
+
     # echo output location/filename
-    test -f "$out/$baseout.dv" && echo "$me output $out/$baseout.dv" || { echo "$me No output file found, error, exiting" ; exit 1; }
+    test -f "$out/$baseout.mov" && echo "$me output $out/$baseout.mov" || { echo "$me No output file found, error, exiting" ; exit 1; }
     
     echo #empty line
     
diff --git a/bin/toX264crf b/bin/toX264crf
--- a/bin/toX264crf
+++ b/bin/toX264crf
@@ -38,18 +38,24 @@ while [ $# -gt 0 ]; do
         encode "$file"
         
         wait
+        
+    # unique output filename
+    baseout="$base" 
+    while [ -f "$out/$baseout.mp4" ] ; do
+        baseout="$base.$RANDOM"
+    done
 
     # if there is audio, then mux video + audio, else just mv video to final location.
     if hasAudio "$file" ; then
         echo "hasAudio, muxing"
-        ffmpeg -y -i "$tmpdir/$base.video.mp4" -i "$tmpdir/$base.m4a" -acodec copy -vcodec copy "$out/$base.mp4" -loglevel panic -movflags +faststart </dev/null
+        ffmpeg -y -i "$tmpdir/$base.video.mp4" -i "$tmpdir/$base.m4a" -acodec copy -vcodec copy "$out/$baseout.mp4" -loglevel panic -movflags +faststart </dev/null
     else
         echo "noAudio, just moving"
-        mv "$tmpdir/$base.video.mp4" "$out/$base.mp4" 
+        mv "$tmpdir/$base.video.mp4" "$out/$baseout.mp4" 
     fi
     
     # echo output location/filename
-    test -f "$out/$base.mp4" && echo "$me output $out/$base.mp4" || { echo "$me No output file found, error, exiting" ; exit 1; }
+    test -f "$out/$baseout.mp4" && echo "$me output $out/$baseout.mp4" || { echo "$me No output file found, error, exiting" ; exit 1; }
     
     echo #empty line
     
