modified:   bin/MXFdownmix 	new file:   bin/README.md 	modified:   bin/toAAC 	modified:   bin/toDV 	deleted:    bin/toOPUS 	copied:     bin/toVP9 -> bin/toVORBIS 	modified:   bin/toVP9 	modified:   bin/toX264crf

diff --git a/bin/toVP9 b/bin/toVP9
--- a/bin/toVP9
+++ b/bin/toVP9
@@ -1,88 +1,68 @@
 #!/bin/bash
-
-# functions
-encode() { # put your encoding settings here
-
-    when=$(date +%Y%m%d%H%M%S)
-    FFREPORT=file="$log/$baseext.$when.log":level=32 \
-    \
-    ffmpeg -hide_banner -loglevel quiet -i "$file" -af volume="$r128"dB -vn -y "$tmpdir/$base.wav" # to pcm tmp 
-    
-    # opusenc defaults
-    opusenc --quiet "$tmpdir/$base.wav" "$tmpdir/$base.opus"
-    
-}
-# help
-    if [ $# -eq 0 ]; then echo "anything video to VP9"; exit 1; fi
-    
+# set -x
 # script name into "$me"
 me=$(basename $BASH_SOURCE)
 
-echo "$me"
+# functions
+encode()  { # put your encoding settings here
 
-# source config file and tmpdir generator and timer
+    when=$(date +%Y%m%d%H%M%S)
+    FFREPORT=file="$log/$baseext.$when.$RANDOM.$me.log":level=40 \
+    \
+    ffmpeg -hide_banner -i "$file" -aspect 16:9 -vf yadif=0 -c:v libvpx-vp9 -crf 10 -b:v 0 -an "$tmpdir/$base.video.webm" </dev/null 
+    # </dev/null is some sort of null input, so that script will work when in bg as well
+    # -loglevel panic -stats
+}
+
+# ffmpeg -i input.mp4 -c:v libvpx-vp9 -crf 10 -b:v 0 -c:a libvorbis output.webm
+
+# help
+    if [ $# -eq 0 ]; then echo "anything to VP9 crf mode with some vorbis audio"; exit 1; fi
+
+# source config file which includes tmpdir generator and timer
 config="$HOME/bin/singularity.cfg"
-if [ -e "$config" ]; then
-    source "$config"
-else 
-    echo "$config does not exist"; exit 1
-fi 
+test -f "$config" && source "$config" >/dev/null || { echo "$config does not exist" ; exit 1; }
+# and timer
 source "$HOME/bin/timer_func" # not a big deal if this fails
 
-# indirect? (if called from another script then also overwrite $out)
-# example call: thisScript scriptcall "/some/writable/dir" inputfile
-    if [ "$1" == "scriptcall" ]; then # this is called from another script
-        # now check 2nd parameter (new $out) which should be writable and directory
-        if [ -d "$2" ] && [ -w "$2" ] ;  then 
-            echo "$2 is writable directory"  
-            out="$2" # new writable output directory is the one that was passed by calling script (its $tmp)
-            shift ; shift # remove 1st two, so only files are left for further loops
-        else 
-            echo "$2 is not directory or writable"; exit 1
-        fi
-    else
-        echo "direct call"        
-    fi
-
-# checks
-command -v mediainfo >/dev/null 2>&1 || { >&2 echo "I need mediainfo installed." ; exit 1; }
-command -v ffmpeg >/dev/null 2>&1 || { >&2 echo "I need ffmpeg installed." ; exit 1; }
-
-
-# main
+# main loop
 while [ $# -gt 0 ]; do
+
     file=$(readlink -f "$1")
-    echo "$me inp $file"
-    baseext=$(basename "${1}")     # basename, like                file.flac
-    base="${baseext%.*}"           # basename without extension    file
-    echo "$me out $out/$base.m4a"
+    baseext=$(basename "${1}")      # file.ext
+    base="${baseext%.*}"            # file
+        # skip file entirely if there is no video
+        hasVideo "$file" || { >&2 echo "No Video in $file" ; shift; continue; }
+        # encode audio in background (remove >/dev/null 2>&1 when debuging)
+        hasAudio "$file" && toVORBIS scriptcall "$tmpdir" "$1" >/dev/null 2>&1 &
+        # encode video
+        echo "$me encoding $file"
+        encode "$file"
+        
+        wait
 
-    hasAudio "$file" || { >&2 echo "No Audio in $file" ; shift; continue; } # "continue" should skip to next file in this while loop.
-    
-    if $(isMXF "$file"); then
-    echo "MXF detected"
-    MXFdownmix "$file" "$tmpdir"
-    file="$tmpdir/$base.Stereo.wav" # this is the new target for the r128 and encode function now
+    # if there is audio, then mux video + audio, else just mv video to final location.
+    if hasAudio "$file" ; then
+        echo "hasAudio, muxing"
+        ffmpeg -y -i "$tmpdir/$base.video.webm" -i "$tmpdir/$base.ogg" -acodec copy -vcodec copy "$out/$base.webm" -loglevel panic </dev/null
+    else
+        echo "noAudio, just moving"
+        mv "$tmpdir/$base.video.webm" "$out/$base.webm" 
     fi
     
-    # IS r128 = true, then encode with that in mind ...
-    if [ "$EBUR128" == "true" ]; then # this is set in config
-        r128=$(r128corection "$file")
-        echo "$r128"
-    else    
-        r128="0"
-    fi
+    # echo output location/filename
+    test -f "$out/$base.webm" && echo "$me output $out/$base.webm" || { echo "$me No output file found, error, exiting" ; exit 1; }
     
-    # action
-    encode # function
+    echo #empty line
     
-    # move file out of tmp to its final location
-    mv "$tmpdir/$base.opus" "$out/$base.opus" # will replace files with same name 
-    
-
 shift
-done
+done 
 
 echo "$me done in" $(timer $tmr)
 
+flite -voice rms "I did something" >/dev/null 2>&1
+
 stty sane
+
+
+
