deleted:    bin/deleteme/toAACminimodule 	modified:   bin/toAAC 	modified:   bin/toX264crf

diff --git a/bin/toX264crf b/bin/toX264crf
--- a/bin/toX264crf
+++ b/bin/toX264crf
@@ -6,7 +6,7 @@ encode()  { # put your encoding settings here
     when=$(date +%Y%m%d%H%M%S)
     FFREPORT=file="$log/$baseext.$when.log":level=32 \
     \
-    ffmpeg -hide_banner -i "$file" -pix_fmt yuv420p -aspect 16:9 -vf yadif=0 -vcodec libx264 -preset fast -tune film -crf 21 -threads 0 -an "$tmpdir/$base.video.mp4" -loglevel info
+    ffmpeg -hide_banner -i "$file" -pix_fmt yuv420p -aspect 16:9 -vf yadif=0 -vcodec libx264 -preset fast -tune film -crf 21 -threads 0 -an "$tmpdir/$base.video.mp4" -loglevel panic -stats
     
 }
 
@@ -18,42 +18,49 @@ me=$(basename $BASH_SOURCE)
 
 # source config file which includes tmpdir generator and timer
 config="$HOME/bin/singularity.cfg"
-test -f "$config" && source "$config" || { echo "$config does not exist" ; exit 1; }
+test -f "$config" && source "$config" >/dev/null || { echo "$config does not exist" ; exit 1; }
 # and timer
 source "$HOME/bin/timer_func" # not a big deal if this fails
 
 # checks
-command -v mediainfo >/dev/null 2>&1 || { >&2 echo "I need mediainfo installed." ; exit 1; }
-command -v fdkaac >/dev/null 2>&1 || { >&2 echo "I need fdkaac installed." ; exit 1; }
-command -v ffmpeg >/dev/null 2>&1 || { >&2 echo "I need ffmpeg installed." ; exit 1; }
-command -v r128corection >/dev/null 2>&1 || { >&2 echo "I need r128corection script on path" ; exit 1; }
-command -v hasAudio >/dev/null 2>&1 || { >&2 echo "I need hasAudio script on path" ; exit 1; }
-command -v hasVideo >/dev/null 2>&1 || { >&2 echo "I need hasVideo script on path" ; exit 1; }
-command -v MXFdownmix >/dev/null 2>&1 || { >&2 echo "I need MXFdownmix script on path" ; exit 1; }
+command -v mediainfo >/dev/null 2>&1 || { >&2 echo "$me I need mediainfo installed." ; exit 1; }
+command -v fdkaac >/dev/null 2>&1 || { >&2 echo "$me I need fdkaac installed." ; exit 1; }
+command -v ffmpeg >/dev/null 2>&1 || { >&2 echo "$me I need ffmpeg installed." ; exit 1; }
+command -v r128corection >/dev/null 2>&1 || { >&2 echo "$me I need r128corection script on path" ; exit 1; }
+command -v hasAudio >/dev/null 2>&1 || { >&2 echo "$me I need hasAudio script on path" ; exit 1; }
+command -v hasVideo >/dev/null 2>&1 || { >&2 echo "$me I need hasVideo script on path" ; exit 1; }
+command -v MXFdownmix >/dev/null 2>&1 || { >&2 echo "$me I need MXFdownmix script on path" ; exit 1; }
 
 # main loop
 while [ $# -gt 0 ]; do
 
     file=$(readlink -f "$1")
-    echo "input $file"
     baseext=$(basename "${1}")     # basename, like                file.flac
     base="${baseext%.*}"           # basename without extension    file
 
     
         hasVideo "$file" || { >&2 echo "No Video in $file" ; shift; continue; } # "continue" should skip to next file in this while loop.
     
-        hasAudio "$file" && toAAC scriptcall "$tmpdir" "$1" 
+        hasAudio "$file" && toAAC scriptcall "$tmpdir" "$1" >/dev/null 2>&1 & # remove >/dev/null 2>&1 when debuging
         
+        echo "$me encoding $file"
         encode "$file"
         
+        wait
 
     # if there is audio, then mux video + audio, else just mv video to final location.
     if hasAudio "$file" ; then
-        echo "hasAudio"
-        ffmpeg -y -i "$tmpdir/$base.video.mp4" -i "$tmpdir/$base.m4a" -acodec copy -vcodec copy "$out/$base.mp4"
+        echo "hasAudio, muxing"
+        ffmpeg -y -i "$tmpdir/$base.video.mp4" -i "$tmpdir/$base.m4a" -acodec copy -vcodec copy "$out/$base.mp4" -loglevel panic
     else
+        echo "noAudio, just moving"
         mv "$tmpdir/$base.video.mp4" "$out/$base.mp4" 
     fi
+    
+    # echo output location/filename
+    test -f "$out/$base.mp4" && echo "$me output $out/$base.mp4" || { echo "$me No output file found, error, exiting" ; exit 1; }
+    
+    echo #empty line
     
 shift
 done 
