modified:   bin/videothumb

diff --git a/bin/videothumb b/bin/videothumb
--- a/bin/videothumb
+++ b/bin/videothumb
@@ -3,8 +3,7 @@
 # thumbnailer 2016
 # http://ffmpeg.org/ffmpeg-all.html#thumbnail
 # ffmpeg -ss half-of-video -i input.mp4 -vf thumbnail=50 -frames:v 1 out.png
-
-# ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 slitherPro10.mp4
+# ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 input.mp4
 
 tmpdir=/tmp/$RANDOM # < this seems to be working on sid
 trap '[ -n "$tmpdir" ] && rm -fr "$tmpdir"' EXIT
@@ -12,18 +11,28 @@ mkdir -m 700 "$tmpdir" || { echo '!! unable to create a tmpdir' >&2; tmpdir=; ex
 
 # main 
 while [ $# -gt 0 ]; do
+file="$1"
 base=$(basename "${1}")     # basename, like                file.png
 base="${base%.*}"           # basename without extension    file
 dir=$(dirname "${1}")
 
+# check if thumb is allready there
+test -f "$dir/$base.jpg" && { >&2 echo "thumb $dir/$base.jpg allready there, skiping" ; shift; continue; }
+
 # movie duration/2
+dur=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$1")
+halfdur=$(bc -l <<< "$dur / 2.00")
 
-dur=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $1)
+#echo "$dur"
+#echo "$halfdur"
 
-halfdur=$(bc <<< "$dur/2.00")
+echo "$file"
+# The next line will fail if SAR!=1 or when height>width
+ffmpeg -hide_banner -ss "$halfdur" -i "$file" -vf thumbnail=30 -frames:v 1 -vf crop=in_h:in_h,scale=-2:100 "$dir/$base.jpg"
 
-echo "$halfdur"
-
+# -vf scale="'if(gt(a,4/3),320,-1)':'if(gt(a,4/3),-1,240)'" < dunno what this is
+# -loglevel panic -stats 
+# crop=in_h:in_h,scale=-2:200"
 
 shift
 done
